{
  "data": {
    "sketches": [
      {
        "id": "MarkerLine",
        "groupName": "Marker Lines",
        "folderName": "MarkerLines",
        "cover": "MarkerLineCover",
        "sketchList": [
          {"id": "MarkerLine1", "fileName": "MarkerLine1"},
          {"id": "MarkerLine2", "fileName": "MarkerLine2"},
          {"id": "MarkerLine3", "fileName": "MarkerLine3"},
          {"id": "MarkerLine4", "fileName": "MarkerLine4"},
          {"id": "MarkerLine5", "fileName": "MarkerLine5"},
          {"id": "MarkerLine6", "fileName": "MarkerLine6"},
          {"id": "MarkerLine7", "fileName": "MarkerLine7"},
          {"id": "MarkerLine8", "fileName": "MarkerLine8"},
          {"id": "MarkerLine9", "fileName": "MarkerLine9"},
          {"id": "MarkerLine10", "fileName": "MarkerLine10"},
          {"id": "MarkerLine11", "fileName": "MarkerLine11"},
          {"id": "MarkerLine12", "fileName": "MarkerLine12"},
          {"id": "MarkerLine13", "fileName": "MarkerLine13"},
          {"id": "MarkerLine14", "fileName": "MarkerLine14"},
          {"id": "MarkerLine15", "fileName": "MarkerLine15"},
          {"id": "MarkerLine16", "fileName": "MarkerLine16"},
          {"id": "MarkerLine17", "fileName": "MarkerLine17"},
          {"id": "MarkerLine18", "fileName": "MarkerLine18"},
          {"id": "MarkerLine19", "fileName": "MarkerLine19"},
          {"id": "MarkerLine20", "fileName": "MarkerLine20"},
          {"id": "MarkerLine21", "fileName": "MarkerLine21"},
          {"id": "MarkerLine22", "fileName": "MarkerLine22"},
          {"id": "MarkerLine23", "fileName": "MarkerLine23"},
          {"id": "MarkerLine24", "fileName": "MarkerLine24"},
          {"id": "MarkerLine25", "fileName": "MarkerLine25"},
          {"id": "MarkerLine26", "fileName": "MarkerLine26"},
          {"id": "MarkerLine27", "fileName": "MarkerLine27"},
          {"id": "MarkerLine28", "fileName": "MarkerLine28"},
          {"id": "MarkerLine29", "fileName": "MarkerLine29"},
          {"id": "MarkerLine30", "fileName": "MarkerLine30"},
          {"id": "MarkerLine31", "fileName": "MarkerLine31"},
          {"id": "MarkerLine32", "fileName": "MarkerLine32"},
          {"id": "MarkerLine33", "fileName": "MarkerLine33"},
          {"id": "MarkerLine34", "fileName": "MarkerLine34"},
          {"id": "MarkerLine35", "fileName": "MarkerLine35"},
          {"id": "MarkerLine36", "fileName": "MarkerLine36"},
          {"id": "MarkerLine37", "fileName": "MarkerLine37"},
          {"id": "MarkerLine38", "fileName": "MarkerLine38"},
          {"id": "MarkerLine39", "fileName": "MarkerLine39"},
          {"id": "MarkerLine40", "fileName": "MarkerLine40"},
          {"id": "MarkerLine41", "fileName": "MarkerLine41"},
          {"id": "MarkerLine42", "fileName": "MarkerLine42"},
          {"id": "MarkerLine43", "fileName": "MarkerLine43"},
          {"id": "MarkerLine44", "fileName": "MarkerLine44"},
          {"id": "MarkerLine45", "fileName": "MarkerLine45"},
          {"id": "MarkerLine46", "fileName": "MarkerLine46"},
          {"id": "MarkerLine47", "fileName": "MarkerLine47"},
          {"id": "MarkerLine48", "fileName": "MarkerLine48"},
          {"id": "MarkerLine49", "fileName": "MarkerLine49"},
          {"id": "MarkerLine50", "fileName": "MarkerLine50"},
          {"id": "MarkerLine51", "fileName": "MarkerLine51"},
          {"id": "MarkerLine52", "fileName": "MarkerLine52"},
          {"id": "MarkerLine53", "fileName": "MarkerLine53"},
          {"id": "MarkerLine54", "fileName": "MarkerLine54"},
          {"id": "MarkerLine55", "fileName": "MarkerLine55"},
          {"id": "MarkerLine56", "fileName": "MarkerLine56"},
          {"id": "MarkerLine57", "fileName": "MarkerLine57"},
          {"id": "MarkerLine58", "fileName": "MarkerLine58"},
          {"id": "MarkerLine59", "fileName": "MarkerLine59"},
          {"id": "MarkerLine60", "fileName": "MarkerLine60"},
          {"id": "MarkerLine61", "fileName": "MarkerLine61"},
          {"id": "MarkerLine62", "fileName": "MarkerLine62"},
          {"id": "MarkerLine63", "fileName": "MarkerLine63"},
          {"id": "MarkerLine64", "fileName": "MarkerLine64"},
          {"id": "MarkerLine65", "fileName": "MarkerLine65"},
          {"id": "MarkerLine66", "fileName": "MarkerLine66"},
          {"id": "MarkerLine67", "fileName": "MarkerLine67"},
          {"id": "MarkerLine68", "fileName": "MarkerLine68"},
          {"id": "MarkerLine69", "fileName": "MarkerLine69"},
          {"id": "MarkerLine70", "fileName": "MarkerLine70"},
          {"id": "MarkerLine71", "fileName": "MarkerLine71"},
          {"id": "MarkerLine72", "fileName": "MarkerLine72"},
          {"id": "MarkerLine73", "fileName": "MarkerLine73"},
          {"id": "MarkerLine74", "fileName": "MarkerLine74"},
          {"id": "MarkerLine75", "fileName": "MarkerLine75"},
          {"id": "MarkerLine76", "fileName": "MarkerLine76"},
          {"id": "MarkerLine77", "fileName": "MarkerLine77"},
          {"id": "MarkerLine78", "fileName": "MarkerLine78"},
          {"id": "MarkerLine79", "fileName": "MarkerLine79"},
          {"id": "MarkerLine80", "fileName": "MarkerLine80"},
          {"id": "MarkerLine81", "fileName": "MarkerLine81"},
          {"id": "MarkerLine82", "fileName": "MarkerLine82"},
          {"id": "MarkerLine83", "fileName": "MarkerLine83"},
          {"id": "MarkerLine84", "fileName": "MarkerLine84"},
          {"id": "MarkerLine85", "fileName": "MarkerLine85"},
          {"id": "MarkerLine86", "fileName": "MarkerLine86"},
          {"id": "MarkerLine87", "fileName": "MarkerLine87"},
          {"id": "MarkerLine88", "fileName": "MarkerLine88"},
          {"id": "MarkerLine89", "fileName": "MarkerLine89"},
          {"id": "MarkerLine90", "fileName": "MarkerLine90"},
          {"id": "MarkerLine91", "fileName": "MarkerLine91"},
          {"id": "MarkerLine92", "fileName": "MarkerLine92"},
          {"id": "MarkerLine93", "fileName": "MarkerLine93"},
          {"id": "MarkerLine94", "fileName": "MarkerLine94"},
          {"id": "MarkerLine95", "fileName": "MarkerLine95"},
          {"id": "MarkerLine96", "fileName": "MarkerLine96"},
          {"id": "MarkerLine97", "fileName": "MarkerLine97"}
        ]
      }

    ]
  }
}
